database:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5435:5432"
  environment:
    POSTGRES_USER: catalogus
    POSTGRES_DB: catalogus
    POSTGRES_PASSWORD: insecure

solr:
  build: ./solr
  ports:
    - "8983:8983"

ckan:
  build: ./web
  links:
    - database:database
    - solr:solr
  ports:
    - "8105:5000"
  environment:
    CKAN_SQLALCHEMY_URL: postgresql://catalogus:insecure@database/catalogus
    CKAN_SOLR_URL: http://solr:8983/solr/ckan
    CATALOGUS_OBJECTSTORE_PASSWORD: insecure
    JWT_SHARED_SECRET_KEY: insecure
    OBJECTSTORE_TOKEN: insecure
    TEMP_URL_KEY: insecure
  cap_add:
    - SYS_ADMIN
  devices:
    - "/dev/fuse"
