database_ckan:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5435:5432"
  environment:
    POSTGRES_USER: ckan
    POSTGRES_DB: ckan
    POSTGRES_PASSWORD: insecure

solr_ckan:
  build: ./solr
  ports:
    - "8983:8983"
  volumes:
    - data:/opt/solr/server/solr/mycores

ckan:
  build: ./web
  links:
    - database_ckan:database_ckan
    - solr_ckan:solr_ckan
  ports:
    - "8105:8000"
  volumes:
    - ./data:/data
  environment:
    CKAN_SQLALCHEMY_URL: "postgresql://ckan:insecure@database_ckan/ckan"
    CKAN_SOLR_URL: "http://solr_ckan:8983/solr/ckan"
    DEBIAN_FRONTEND: "noninteractive"


