database_ckan:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5435:5432"
  environment:
    POSTGRES_USER: catalogus
    POSTGRES_DB: catalogus
    POSTGRES_PASSWORD: insecure

solr_ckan:
  build: ./solr
  ports:
    - "8983:8983"

ckan:
  build: ./web
  links:
    - database_ckan:database_ckan
    - solr_ckan:solr_ckan
  ports:
    - "8105:5000"
  environment:
    CKAN_SQLALCHEMY_URL: postgresql://catalogus:insecure@database_ckan/catalogus
    CKAN_SOLR_URL: http://solr_ckan:8983/solr/ckan
#    DEBIAN_FRONTEND: "noninteractive"
